phrase:
  project_id: ec87799cc908153b6d91cfb8d976541f
  push:
    sources:
    - file: ./frontend/lang/en-US.json
      params:
        file_format: i18next
        locale_id: 7a88116d641c63b4b7727262c34823ca
  pull:
    targets:
    - file: ./frontend/lang/<locale_name>.json
      params:
        file_format: i18next

      
