phrase:
  access_token: 2e7795ddc27754b089eae342c08f7a05ce3ec51de9737afda5ccba77bb33a86a
  project_id: a2d894203a076ed0172d12bd9be9e24b 

  push:
    sources:
    - file: ./translations/en-US.json
      params:
        file_format: i18next_4
        locale_id: 3d176c94622770b06faeac88b9f63f06
        update_translations: true
          
  pull:
    targets:
    - file: ./translations/en.json
      params:
        file_format: i18next_4
        locale_id: 5498358b2c0a648fa8f6744647ef05f0
        include_empty_translations: true
          
  pull:
    targets:
    - file: ./translations/de.json
      params:
        file_format: i18next_4
        locale_id: ea8eeaef2e65a34594c66449b4102bbb
        include_empty_translations: true
          
          
