phrase:
  project_id: 62b6466e431516dcd1f2a5e7b70fca88
  push:
    sources:
    - file: ./hu-HU.xlsx
      params:
        file_format: xlsx
  pull:
    targets:
    - file: ./it-IT.xlsx
      params:
        file_format: i18next
  pull:
    targets:
    - file: ./es-ES.xlsx
     params:
        file_format: i18next
