phrase:
  access_token: 2e7795ddc27754b089eae342c08f7a05ce3ec51de9737afda5ccba77bb33a86a
  project_id: d8b77fd44f98aa3a9793942ac1c66f66 

  push:
    sources:
    - file: ./translations/test.json
      params:
        file_format: i18next_4
        locale_id: en
        update_translations: true
        autotranslate: true
        
        
          
  pull:
    targets:
    - file: ./translations/en.json
      params:
        file_format: i18next_4
        locale_id: en
        include_empty_translations: true
          
  pull:
    targets:
    - file: ./translations/de.json
      params:
        file_format: i18next_4
        locale_id: de
        include_empty_translations: true
          
          
